wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.12
    start_time: 1669068035.747777
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.9.12
      5: 0.13.5
      8:
      - 3
      - 5
batch_size:
  desc: null
  value: 2
lr:
  desc: null
  value: 0.0061521041159696985
